<a href="https://colab.research.google.com/github/ajohn256/Deep-Learning-With-Pytorch/blob/main/Gradients_and_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import torch

In [44]:
x = torch.rand(3,requires_grad=True)

In [45]:
x

tensor([0.6921, 0.0556, 0.7544], requires_grad=True)

In [46]:
x

tensor([0.6921, 0.0556, 0.7544], requires_grad=True)

In [47]:
y = x+2

In [48]:
y#calculating gradients with back propagation

tensor([2.6921, 2.0556, 2.7544], grad_fn=<AddBackward0>)

In [49]:
z = y*y*2

In [50]:
z

tensor([14.4953,  8.4507, 15.1730], grad_fn=<MulBackward0>)

In [51]:
z.mean()

tensor(12.7063, grad_fn=<MeanBackward0>)

In [52]:
print(x.grad)

None


In [53]:
# z.backward()
x

tensor([0.6921, 0.0556, 0.7544], requires_grad=True)

In [58]:
#prevent gradient tracking by;
#>requires_grad_(false)
# x.detach()
#>with torch.no_grad()
# x.requires_grad_(False)

with torch.no_grad():
  z = x*x
  print(z)

tensor([0.4791, 0.0031, 0.5691])


In [59]:
x

tensor([0.6921, 0.0556, 0.7544], requires_grad=True)

In [63]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
  model_out = (weights*3).sum()
  model_out.backward()
  print(weights.grad)
  #to prevent accumulation of gradients always clear the gradients in weights
  weights.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [68]:
#using optimizer
# optimizer = torch.optim.ASGD(weights,lr=0.01)
# optimizer.step()
# optimizer.zero_grad()