<a href="https://colab.research.google.com/github/ajohn256/Deep-Learning-With-Pytorch/blob/main/Pytorch_Basic_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
x = torch.rand(3,3)
y = torch.rand(9)

In [7]:
print(x)
print(y)

tensor([[0.0127, 0.4179, 0.2522],
        [0.2679, 0.6096, 0.1074],
        [0.6860, 0.1541, 0.2101]])
tensor([0.8812, 0.0429, 0.3299, 0.6771, 0.4507, 0.4508, 0.8838, 0.3418, 0.0515])


In [12]:
y = y.reshape(3,3)

In [13]:
torch.mul(x,y)

tensor([[0.0112, 0.0179, 0.0832],
        [0.1814, 0.2747, 0.0484],
        [0.6063, 0.0527, 0.0108]])

In [14]:
torch.add(x,y)

tensor([[0.8939, 0.4608, 0.5820],
        [0.9450, 1.0603, 0.5582],
        [1.5698, 0.4959, 0.2617]])

In [16]:
torch.sqrt(x)

tensor([[0.1129, 0.6464, 0.5022],
        [0.5176, 0.7808, 0.3276],
        [0.8283, 0.3926, 0.4584]])

In [17]:
x%y

tensor([[0.0127, 0.0316, 0.2522],
        [0.2679, 0.1589, 0.1074],
        [0.6860, 0.1541, 0.0040]])

In [21]:
x.mul_(y) + torch.sqrt(x)

tensor([[0.0954, 0.0012, 0.0576],
        [0.2936, 0.1837, 0.0710],
        [1.0655, 0.0480, 0.0012]])

In [22]:
x

tensor([[7.6864e-03, 1.4183e-06, 2.9856e-03],
        [5.6320e-02, 2.5150e-02, 4.4338e-03],
        [4.1855e-01, 2.1030e-03, 1.4824e-06]])

In [26]:
x[1,:-1]

tensor([0.0563, 0.0251])

In [28]:
x[1,1].item()

0.025149736553430557

In [ ]:
#reshaping tensors

In [29]:
y

tensor([[0.8812, 0.0429, 0.3299],
        [0.6771, 0.4507, 0.4508],
        [0.8838, 0.3418, 0.0515]])

In [32]:
y.view(-1)#1d

tensor([0.8812, 0.0429, 0.3299, 0.6771, 0.4507, 0.4508, 0.8838, 0.3418, 0.0515])

In [33]:
y.view(-1,3)

tensor([[0.8812, 0.0429, 0.3299],
        [0.6771, 0.4507, 0.4508],
        [0.8838, 0.3418, 0.0515]])

In [34]:
x.view(-1,9)

tensor([[7.6864e-03, 1.4183e-06, 2.9856e-03, 5.6320e-02, 2.5150e-02, 4.4338e-03,
         4.1855e-01, 2.1030e-03, 1.4824e-06]])

In [ ]:
#convert numy to tensor

In [35]:
import numpy as np

In [38]:
arr = torch.ones(5)

In [39]:
arr

tensor([1., 1., 1., 1., 1.])

In [40]:
x = arr.numpy()#tensor to numpy

In [41]:
x

array([1., 1., 1., 1., 1.], dtype=float32)

In [42]:
#numpy to tensor
y = torch.from_numpy(x)

In [43]:
y

tensor([1., 1., 1., 1., 1.])